name: Bug Report
description: Report a reproducible bug or unexpected behavior in Rawi.
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please fill out the details below to help us understand and resolve the issue quickly.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide clear, step-by-step instructions to reproduce the bug.
        Example:
        1. Run `rawi <command>`
        2. Enter `input`
        3. Observe `error/unexpected output`
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true
  - type: input
    id: rawi-version
    attributes:
      label: Rawi Version
      description: What version of Rawi are you using? (Run `rawi --version`)
      placeholder: e.g., 0.1.0
    validations:
      required: true
  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: |
        Please provide details about your environment:
        - OS (e.g., Windows 10, macOS Ventura, Ubuntu 22.04)
        - Node.js version (`node -v`)
        - Package manager and version (e.g., `pnpm -v`, `npm -v`, `yarn -v`)
      placeholder: |
        - OS: macOS Sonoma 14.2
        - Node.js: v20.11.0
        - pnpm: 8.15.4
    validations:
      required: true
  - type: textarea
    id: screenshots-or-gifs
    attributes:
      label: Screenshots or GIFs (Optional)
      description: If applicable, add screenshots or animated GIFs to help explain your problem.
      placeholder: You can drag and drop images here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context about the problem here.
