name: Feature Request
description: Suggest an idea for a new feature or enhancement for Rawi.
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or enhancement for Rawi!
        Please fill out the details below to help us understand your idea.
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of the problem you're trying to solve.
      placeholder: As a user, I'm frustrated when [...] because [...].
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. How would this feature work?
      placeholder: I would like Rawi to have a command that...
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've thought about using [...], but it's not ideal because [...].
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context or screenshots about the feature request here.
